config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'dashboards/index'

  root to: "dashboards#index"

  resources :users do
    resources :exercises
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :exercises

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index

  end

  def show
    user = User.find(params[:user_id])
    @exercise = user.exercises.find(params[:id])
  end

  def new
    @exercise = current_user.exercises.new
  end

  def create
    @exercise = current_user.exercises.new(exercise_params)

    if @exercise.save
      flash[:success] = "Exercise has been created"
      redirect_to [current_user, @exercise]
    else
      flash[:alert] = "Exxercise has not been created"
      render :new
    end
  end

  private

    def exercise_params
      params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<div class="jumbotron">
  <h1>Workout Lounge!</h1>
  <p>Show off your workout to your friends and family</p>
</div>

app/views/exercises/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for([current_user, @exercise], html: {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @exercise.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@exercise.errors.count, "error") %>
          prohibited this exercise from being saved:</h2>

          <ul>
            <% @exercise.errros.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :duration_in_min, "Duration (min)" %>
        </div>
        <div class="col-md-10">
          <%= f.number_field :duration_in_min, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout, "Workout details" %><br />
        </div>
        <div class="col-md-10">
          <%= f.text_field :workout, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout, "Activity date" %><br />
        </div>
        <div class="col-md-10">
          <%= f.text_field :workout_date, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: 'btn btn-success btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/index.html.erb
<div class="col-md-8 col-xs-12">
  <%= link_to "New Workout", new_user_exercise_path(current_user), class: "btn btn-success" %>
</div>

app/views/exercises/new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to 'Back', user_exercises_path(current_user),
          class: "btn btn-default link", id: "new-exer-btn"%>
    </div>
  </div>
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div>
    <h1 class="show-header">Showing <%= @exercise.user.full_name %>'s Workout Details</h1>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration (min):</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.duration_in_min %>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout details</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= truncate(@exercise.workout, length: 50) %>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Activity date:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>
  <br />
  <div class="col-xs-12 col-md-10 member">
    <%= link_to 'Back', user_exercises_path(current_user),
        class: "btn btn-success btn-lg link", id: "back-btn"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "shared/header" %>

  <%= render "shared/main" %>

  <%= render "shared/footer" %>


  </body>
</html>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 text-center">
      <footer role="contentinfo">
        <p><small>Coryright &copy; Mashrur Hossain &amp; Emmanuel Asante</small></p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
  <body>
    <header class="banncer">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button"
                    class="navbar-toggle"
                    data-toggle="collapse"
                    data-target="#bs">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
        </button>
        <%= link_to "Athletes Den", root_path, class: "navbar-brand" %>
      </div>

      <div class="navbar-collapse collapse" id="bs">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% unless user_signed_in? %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% else %>
            <li><%= link_to "My Lounge", user_exercises_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <div class="navbar-right">
              <p class="navbar-text">
                Signed in as <%= current_user.email %>
              </p>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |key, message| %>
      <div class="text-center alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>

  </div>
</div>